### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by Rebekahvw** [1024mb-Wits/moodle_plugin#16]
Code coverage not at 50% yet

**Comment by dkb18** [comment]
Large portions of code are graphic intensive and cannot be tested through code.  Will try to get it back up to 50% yet

**Comment by wasimrahiman** [comment]
Code coverage has been increased to 50% but now we are having an issue updating the badge on GitHub

**Comment by Rebekahvw** [comment]
Code has reached 50% coverage and badge is working
