### ISSUE TITLE
Moving nodes issue

### ISSUE THREAD

**Issue by Rebekahvw** [1024mb-Wits/moodle_plugin#5]
Problem with moving nodes: nodes move to the position where we drag it to, but you can’t see the node move between the start and end point while you drag it.

**Comment by yasirad** [comment]
Problem with adding nodes: if we add a node on top of another node, the following problems arise:
a. If you attempt to delete the node place on top of the other node, the widget erases part of the outline of the node below it
b. If you attempt to move the node place on top of the other node, the widget erases part of the outline of the node below it

**Comment by yasirad** [comment]
Connecting nodes is not yet working
